pub mod user;
pub mod db;
pub mod note;
pub mod todo;
pub mod area;
pub mod media;
pub mod tag;
pub mod template;
pub mod component;
pub mod categorie;
pub mod event;
pub mod card;
use sea_orm::prelude::*;
use sea_orm_migration::prelude::*;
use serde::{Deserialize, Serialize};